/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.pagamento.view;

import br.com.ifba.prg03projetosgcr.cliente.controller.ClienteController;
import br.com.ifba.prg03projetosgcr.cliente.entity.Cliente;
import br.com.ifba.prg03projetosgcr.config.SpringContext;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;
import org.springframework.stereotype.Component;
/**
 *
 * @author joaol
 */
public class BuscaCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscaCliente.class.getName());
    
    // Variável que vai segurar o cliente que o usuário escolheu na tabela
    @Getter
    private Cliente clienteSelecionado;
    
    /**
     * Creates new form BuscaCliente
     */
    public BuscaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //preenche a tabela com todos os clientes no exato momento que a tela abre
        atualizarTabela(""); 
        
        //para a pesquisa em tempo real
        configurarPesquisaDinamica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnSelecionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPesquisar.setText("Pesquisar...");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Número"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setResizable(false);
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        btnSelecionarCliente.setBackground(new java.awt.Color(0, 102, 51));
        btnSelecionarCliente.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnSelecionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionarCliente.setText("Selecionar Cliente");
        btnSelecionarCliente.addActionListener(this::btnSelecionarClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnSelecionarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelecionarCliente)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    private void atualizarTabela(String busca) {
        try {
            ClienteController clienteController = SpringContext.getBean(ClienteController.class);
            java.util.List<Cliente> resultados;
            
            // Se o campo estiver vazio ou com o texto padrão de ajuda, busca todos!
            if (busca.isEmpty() || busca.equals("Pesquisar...")) {
                resultados = clienteController.findAll();
            } else {
                resultados = clienteController.findByNome(busca);
            }
            
            // Atualiza a interface gráfica
            javax.swing.table.DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
            modelo.setNumRows(0); // Limpa as linhas antigas
            
            for (Cliente c : resultados) {
                modelo.addRow(new Object[]{
                    c.getId(),
                    c.getNome(),
                    c.getTelefone()
                });
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao conectar com o banco de dados: " + e.getMessage(), 
                "Erro Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void configurarPesquisaDinamica() {
        txtPesquisar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { pesquisar(); }
            
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { pesquisar(); }
            
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { pesquisar(); }
            
            private void pesquisar() {
                // O invokeLater garante que a interface não vai "engasgar" se o user digitar muito rápido
                javax.swing.SwingUtilities.invokeLater(() -> {
                    atualizarTabela(txtPesquisar.getText().trim());
                });
            }
        });
    }
        
    
    private void btnSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClienteActionPerformed
        // Descobre qual linha da tabela o usuário clicou
        int linhaSelecionada = tblClientes.getSelectedRow();

        // Valida se ele realmente clicou em alguém
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, clique em um cliente na tabela primeiro.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Pega o ID da coluna 0 
            Long idCliente = (Long) tblClientes.getValueAt(linhaSelecionada, 0);

            // Vai no banco buscar o cliente COMPLETO 
            ClienteController clienteController = SpringContext.getBean(ClienteController.class);
            this.clienteSelecionado = clienteController.findById(idCliente);

            // fecha a janelinha e devolve o controle para a tela de trás
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao resgatar o cliente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelecionarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BuscaCliente dialog = new BuscaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
