/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.pagamento.view;

import br.com.ifba.prg03projetosgcr.pagamento.controller.PagamentoController;
import br.com.ifba.prg03projetosgcr.pagamento.entity.FormaPagamento;
import br.com.ifba.prg03projetosgcr.pagamento.entity.Pagamento;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class EditarPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarPagamento.class.getName());
    
    private Pagamento pagamentoAtual;
    private ListarPagamentos telaPrincipal;
    @Autowired
    private PagamentoController pagamentoController;
    
    /**
     * Creates new form EditarPagamento
     */
    public EditarPagamento() {
        initComponents();
        
        for (FormaPagamento fp : FormaPagamento.values()) {
            cbxFormaPagamento.addItem(fp.name());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void preencherDados(Pagamento pagamento, ListarPagamentos telaPrincipal){
        this.pagamentoAtual = pagamento;
        this.telaPrincipal = telaPrincipal; // Guarda a referencia
        
        //Preenche e bloqueia o campo cliente
        txtCliente.setText(pagamento.getCliente().getNome());
        txtCliente.setEditable(false);
        
        //preenche o valor
        txtValorPagamento.setText(String.valueOf(pagamento.getValorTotal()));
        
        //preenche a forma de pagamento no combobox
        cbxFormaPagamento.setSelectedItem(pagamento.getFormaPagamento());
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblFormaPagamento = new javax.swing.JLabel();
        cbxFormaPagamento = new javax.swing.JComboBox<>();
        lblValorPagamento = new javax.swing.JLabel();
        txtValorPagamento = new javax.swing.JTextField();
        btnEditarPagamento = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblTitulo.setText("Edite o Pagamento");

        lblCliente.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblCliente.setText("Cliente:");

        txtCliente.setEditable(false);
        txtCliente.addActionListener(this::txtClienteActionPerformed);

        lblFormaPagamento.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblFormaPagamento.setText("Forma de pagamento:");

        cbxFormaPagamento.addActionListener(this::cbxFormaPagamentoActionPerformed);

        lblValorPagamento.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblValorPagamento.setText("Valor de Pagamento:");

        txtValorPagamento.addActionListener(this::txtValorPagamentoActionPerformed);

        btnEditarPagamento.setBackground(new java.awt.Color(0, 102, 51));
        btnEditarPagamento.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnEditarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPagamento.setText("Editar Pagamento");
        btnEditarPagamento.addActionListener(this::btnEditarPagamentoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFormaPagamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEditarPagamento)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblValorPagamento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorPagamento))
                .addGap(54, 54, 54)
                .addComponent(btnEditarPagamento)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void cbxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFormaPagamentoActionPerformed

    private void txtValorPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPagamentoActionPerformed

    private void btnEditarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPagamentoActionPerformed
        try{
            //captura e converte o novo valor
            //troca a virgula por ponto
            String valorTexto = txtValorPagamento.getText().replace(",", ".");
            Double novoValor = Double.parseDouble(valorTexto);
            
            if(novoValor <= 0){
                JOptionPane.showMessageDialog(this,
                        "O valor deve ser maior que zero! ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Pega no item que o utilizador escolheu e converte para texto (String)
            String textoSelecionado = cbxFormaPagamento.getSelectedItem().toString();

            // 2. Pede ao Enum para procurar o valor exato correspondente a esse texto
            FormaPagamento novaForma = FormaPagamento.valueOf(textoSelecionado);

            //atualiza apenas os dados permitidos
            pagamentoAtual.setValorTotal(novoValor);
            pagamentoAtual.setFormaPagamento(novaForma);
            
            //envia pro controller
            pagamentoController.update(pagamentoAtual);
            
            if(this.telaPrincipal != null){
                this.telaPrincipal.atualizarTabela();
                this.telaPrincipal.atualizarPainelFinanceiro();
            }
            
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um valor numérico válido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar pagamento: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarPagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPagamento;
    private javax.swing.JComboBox<String> cbxFormaPagamento;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorPagamento;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtValorPagamento;
    // End of variables declaration//GEN-END:variables
}
