#Importa o arquivo de configura\u00e7\u00e3o
spring.config.import=file:.env.properties

spring.application.name=prg03projetosgcr

# Configura\u00e7\u00f5es de Conex\u00e3o com o NEON
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura\u00e7\u00f5es do Spring Data JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Atualiza as tabelas automaticamente (mant\u00e9m os dados)
spring.jpa.hibernate.ddl-auto=update