/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.produto.view;

import br.com.ifba.prg03projetosgcr.produto.controller.ProdutoController;
import br.com.ifba.prg03projetosgcr.produto.entity.Produto;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


/**
 *
 * @author joaol
 */
@Component
public class CadastrarProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarProduto.class.getName());
    
    private ListarProdutos listarProdutos;
    @Autowired
    private ProdutoController produtoController;
    
    public void setListarProdutos(ListarProdutos listarProdutos) {
        this.listarProdutos = listarProdutos;
    }
    
    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
        
        configurarCalculadoraLucro();
    }
    
    private void calcularPrecoIdeal() {
        try {
            // Pega os textos digitados e troca vírgula por ponto 
            String textoCusto = txtPrecoCusto.getText().trim().replace(",", ".");
            String textoMargem = txtMargemLucro.getText().trim().replace(",", ".");
            
            // Só faz a conta se os dois campos estiverem preenchidos
            if (!textoCusto.isEmpty() && !textoMargem.isEmpty()) {
                double custo = Double.parseDouble(textoCusto);
                double margem = Double.parseDouble(textoMargem);
                
                // Custo + (Custo * (Margem / 100))
                double precoIdeal = custo + (custo * (margem / 100.0));
                
                // Formata o resultado com 2 casas decimais e joga no campo de Preço da Unidade
                // Obs: Usei Locale.US para garantir que saia com ponto (ex: 45.50) e não quebre o botão salvar
                txtPrecoSugerido.setText(String.format(java.util.Locale.US, "%.2f", precoIdeal));
            }
        } catch (NumberFormatException e) {
            // Se o usuário digitar "abc" sem querer, o sistema ignora e não quebra a tela
        }
    }
    
    private void configurarCalculadoraLucro() {
        // Cria um ouvinte de teclado
        java.awt.event.KeyAdapter leituraTeclado = new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calcularPrecoIdeal(); // Chama o cálculo sempre que uma tecla for solta
            }
        };
        
        // Pendura o ouvinte nos campos de Custo e Margem
        txtPrecoCusto.addKeyListener(leituraTeclado);
        txtMargemLucro.addKeyListener(leituraTeclado);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTituloCadastrarProduto = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblPrecoCusto = new javax.swing.JLabel();
        lblCalculeLucro = new javax.swing.JLabel();
        txtPrecoCusto = new javax.swing.JTextField();
        lblMargemLucro = new javax.swing.JLabel();
        txtMargemLucro = new javax.swing.JTextField();
        lblPrecoSugerido = new javax.swing.JLabel();
        txtPrecoSugerido = new javax.swing.JTextField();
        lblEstoqueAtual = new javax.swing.JLabel();
        txtEstoqueAtual = new javax.swing.JTextField();
        lblPrecoUnidade = new javax.swing.JLabel();
        txtPrecoUnidade = new javax.swing.JTextField();
        btnCadastrarProduto = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        rbtnAtivar = new javax.swing.JRadioButton();
        rbtnDesativar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloCadastrarProduto.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTituloCadastrarProduto.setText("Cadastrar novo produto");

        lblNomeProduto.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNomeProduto.setText("Nome do produto:");

        txtNomeProduto.addActionListener(this::txtNomeProdutoActionPerformed);

        lblDescricao.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        txtDescricao.addActionListener(this::txtDescricaoActionPerformed);

        lblPrecoCusto.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblPrecoCusto.setText("Preço de custo");

        lblCalculeLucro.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblCalculeLucro.setText("Calcule seu lucro");

        lblMargemLucro.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMargemLucro.setText("Margem de lucro (%)");

        lblPrecoSugerido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPrecoSugerido.setText("Preço de venda ideal");

        txtPrecoSugerido.setText("R$");

        lblEstoqueAtual.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblEstoqueAtual.setText("Estoque Atual");

        txtEstoqueAtual.addActionListener(this::txtEstoqueAtualActionPerformed);

        lblPrecoUnidade.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPrecoUnidade.setText("Preço unidade");

        txtPrecoUnidade.setText("R$");
        txtPrecoUnidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecoUnidadeFocusGained(evt);
            }
        });
        txtPrecoUnidade.addActionListener(this::txtPrecoUnidadeActionPerformed);

        btnCadastrarProduto.setBackground(new java.awt.Color(0, 102, 51));
        btnCadastrarProduto.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnCadastrarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.addActionListener(this::btnCadastrarProdutoActionPerformed);

        lblStatus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblStatus.setText("Status");

        buttonGroup1.add(rbtnAtivar);
        rbtnAtivar.setSelected(true);
        rbtnAtivar.setText("Ativar");
        rbtnAtivar.addActionListener(this::rbtnAtivarActionPerformed);

        buttonGroup1.add(rbtnDesativar);
        rbtnDesativar.setText("Desativar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblTituloCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNomeProduto)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                    .addComponent(txtNomeProduto))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEstoqueAtual)
                                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblStatus)
                            .addComponent(rbtnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoSugerido)
                            .addComponent(txtMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPrecoCusto)
                                        .addComponent(lblMargemLucro))
                                    .addGap(44, 44, 44))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblCalculeLucro)
                                    .addGap(73, 73, 73)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoUnidade))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblCalculeLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecoCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMargemLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecoSugerido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTituloCadastrarProduto)
                        .addGap(34, 34, 34)
                        .addComponent(lblNomeProduto)
                        .addGap(5, 5, 5)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstoqueAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAtivar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnDesativar)
                .addGap(18, 18, 18)
                .addComponent(lblPrecoUnidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnCadastrarProduto)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtEstoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueAtualActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        try {
            String nome = txtNomeProduto.getText().trim();
            String descricao = txtDescricao.getText().trim();
            String estoqueTexto = txtEstoqueAtual.getText().trim();
            String precoUnidadeTexto = txtPrecoUnidade.getText().trim();
            String precoCustoTexto = txtPrecoCusto.getText().trim(); 

            // Validação básica de tela
            if (nome.isEmpty() || precoUnidadeTexto.isEmpty() || estoqueTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha o Nome, Estoque e Preço da unidade!", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tratamento seguro de Números (Troca vírgula por ponto automaticamente)
            int estoque = Integer.parseInt(estoqueTexto);
            double precoUnidade = Double.parseDouble(precoUnidadeTexto.replace(",", "."));
            
            // O preço de custo pode ser opcional. Se estiver vazio, salva como 0.0
            double precoCusto = 0.0;
            if (!precoCustoTexto.isEmpty()) {
                precoCusto = Double.parseDouble(precoCustoTexto.replace(",", "."));
            }

            // Leitura do Status (Pega a bolinha "Ativar")
            boolean ativo = rbtnAtivar.isSelected(); 

            // Monta a entidade e manda para o banco (Persistência)
            Produto produto = new Produto();
            produto.setNome(nome);
            produto.setDescricao(descricao);
            produto.setQuantidadeEstoque(estoque);
            produto.setPrecoUnidade(precoUnidade);
            produto.setPrecoCusto(precoCusto);
            produto.setAtivo(ativo);

            produtoController.save(produto);

            JOptionPane.showMessageDialog(this, 
                "Produto adicionado ao estoque com sucesso!", 
                "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Recarrega a tabela na tela de trás e fecha a janelinha
            if (listarProdutos != null) {
                listarProdutos.atualizarTabela();
            }
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, digite apenas números válidos no Preço e no Estoque.", 
                "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, 
                ex.getMessage(), "Erro na Regra de Negócio", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro interno ao salvar o produto.", "Erro Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void rbtnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAtivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAtivarActionPerformed

    private void txtPrecoUnidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoUnidadeFocusGained
        String textoAtual = txtPrecoUnidade.getText().trim();
        
        // Se o campo tiver com o texto padrão, ele limpa para facilitar a digitação
        if (textoAtual.equals("R$")) {
            txtPrecoUnidade.setText("");
        }
    }//GEN-LAST:event_txtPrecoUnidadeFocusGained

    private void txtPrecoUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoUnidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblCalculeLucro;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstoqueAtual;
    private javax.swing.JLabel lblMargemLucro;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPrecoCusto;
    private javax.swing.JLabel lblPrecoSugerido;
    private javax.swing.JLabel lblPrecoUnidade;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloCadastrarProduto;
    private javax.swing.JRadioButton rbtnAtivar;
    private javax.swing.JRadioButton rbtnDesativar;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueAtual;
    private javax.swing.JTextField txtMargemLucro;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCusto;
    private javax.swing.JTextField txtPrecoSugerido;
    private javax.swing.JTextField txtPrecoUnidade;
    // End of variables declaration//GEN-END:variables
}
