/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.produto.view;

import br.com.ifba.prg03projetosgcr.categoria.controller.CategoriaController;
import br.com.ifba.prg03projetosgcr.categoria.entity.Categoria;
import br.com.ifba.prg03projetosgcr.produto.controller.ProdutoController;
import br.com.ifba.prg03projetosgcr.produto.entity.Produto;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class EditarProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarProduto.class.getName());
   
    @Autowired
    private ProdutoController produtoController;
    @Autowired
    private CategoriaController categoriaController;

    private ListarProdutos listarProdutos;
    private Produto produtoEmEdicao; 
    
    private Categoria categoriaSelecionada;

    public void setListarProdutos(ListarProdutos listarProdutos) {
        this.listarProdutos = listarProdutos;
    }
    
    public void preencherCampos(Produto produto) {
        this.produtoEmEdicao = produto; // Guarda o produto na memória
        this.categoriaSelecionada = produto.getCategoria();
        
        // Joga os dados do banco para os campos de texto da tela
        txtNomeProduto.setText(produto.getNome());
        txtDescricao.setText(produto.getDescricao() != null ? produto.getDescricao() : "");
        txtEstoque.setText(String.valueOf(produto.getQuantidadeEstoque()));
        
        // Formata os preços com ponto para não dar erro se o usuário for editar
        txtPrecoUnidade.setText(String.valueOf(produto.getPrecoUnidade()));
        txtPrecoCusto.setText(String.valueOf(produto.getPrecoCusto()));
        
        if (this.categoriaSelecionada != null) {
            txtCategoria.setText(this.categoriaSelecionada.getNome());
        } else {
            txtCategoria.setText("Sem Categoria");
        }
        
        // Marca a bolinha de status correta
        if (produto.isAtivo()) {
            rbtnAtivar.setSelected(true);
        } else {
            rbtnDesativar.setSelected(true); 
        }
        
    }
    
        
    private void calcularPrecoIdeal() {
        try {
            // Pega os textos digitados e troca vírgula por ponto 
            String textoCusto = txtPrecoCusto.getText().trim().replace(",", ".");
            String textoMargem = txtMargemLucro.getText().trim().replace(",", ".");
            
            // Só faz a conta se os dois campos estiverem preenchidos
            if (!textoCusto.isEmpty() && !textoMargem.isEmpty()) {
                double custo = Double.parseDouble(textoCusto);
                double margem = Double.parseDouble(textoMargem);
                
                // Custo + (Custo * (Margem / 100))
                double precoIdeal = custo + (custo * (margem / 100.0));
                
                // Formata o resultado com 2 casas decimais e joga no campo de Preço da Unidade
                // Obs: Usei Locale.US para garantir que saia com ponto (ex: 45.50) e não quebre o botão salvar
                txtPrecoSugerido.setText(String.format(java.util.Locale.US, "%.2f", precoIdeal));
            }
        } catch (NumberFormatException e) {
            // Se o usuário digitar "abc" sem querer, o sistema ignora e não quebra a tela
        }
    }
    
    private void configurarCalculadoraLucro() {
        // Cria um ouvinte de teclado
        java.awt.event.KeyAdapter leituraTeclado = new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calcularPrecoIdeal(); // Chama o cálculo sempre que uma tecla for solta
            }
        };
        
        // Pendura o ouvinte nos campos de Custo e Margem
        txtPrecoCusto.addKeyListener(leituraTeclado);
        txtMargemLucro.addKeyListener(leituraTeclado);
    }
    
    /**
     * Creates new form CadastrarProduto
     */
    public EditarProduto() {
        initComponents();
        
        calcularPrecoIdeal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTituloEditarProduto = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblPrecoCusto = new javax.swing.JLabel();
        lblTituloCalculeLucro = new javax.swing.JLabel();
        txtPrecoCusto = new javax.swing.JTextField();
        lblMargemLucro = new javax.swing.JLabel();
        txtMargemLucro = new javax.swing.JTextField();
        lblPrecoSugerido = new javax.swing.JLabel();
        txtPrecoSugerido = new javax.swing.JTextField();
        lblEstoque = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        lblPrecoUnidade = new javax.swing.JLabel();
        txtPrecoUnidade = new javax.swing.JTextField();
        btnConfirmarAlteracoes = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        rbtnAtivar = new javax.swing.JRadioButton();
        rbtnDesativar = new javax.swing.JRadioButton();
        lblEstoqueAtual1 = new javax.swing.JLabel();
        btnCategoria = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloEditarProduto.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTituloEditarProduto.setText("Editar Produto");

        lblNomeProduto.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNomeProduto.setText("Nome do produto:");

        txtNomeProduto.addActionListener(this::txtNomeProdutoActionPerformed);

        lblDescricao.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        txtDescricao.addActionListener(this::txtDescricaoActionPerformed);

        lblPrecoCusto.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblPrecoCusto.setText("Preço de custo");

        lblTituloCalculeLucro.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblTituloCalculeLucro.setText("Calcule seu lucro");

        lblMargemLucro.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMargemLucro.setText("Margem de lucro (%)");

        lblPrecoSugerido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPrecoSugerido.setText("Preço de venda ideal");

        txtPrecoSugerido.setText("R$");

        lblEstoque.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblEstoque.setText("Estoque Atual");

        txtEstoque.addActionListener(this::txtEstoqueActionPerformed);

        lblPrecoUnidade.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblPrecoUnidade.setText("Preço unidade");

        txtPrecoUnidade.setText("R$");
        txtPrecoUnidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecoUnidadeFocusGained(evt);
            }
        });

        btnConfirmarAlteracoes.setBackground(new java.awt.Color(0, 102, 51));
        btnConfirmarAlteracoes.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnConfirmarAlteracoes.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarAlteracoes.setText("Confirmar Alterações");
        btnConfirmarAlteracoes.addActionListener(this::btnConfirmarAlteracoesActionPerformed);

        lblStatus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblStatus.setText("Status");

        buttonGroup1.add(rbtnAtivar);
        rbtnAtivar.setSelected(true);
        rbtnAtivar.setText("Ativar");
        rbtnAtivar.addActionListener(this::rbtnAtivarActionPerformed);

        buttonGroup1.add(rbtnDesativar);
        rbtnDesativar.setText("Desativar");

        lblEstoqueAtual1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblEstoqueAtual1.setText("Categoria:");

        btnCategoria.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnCategoria.setText("Selecionar Categoria");
        btnCategoria.addActionListener(this::btnCategoriaActionPerformed);

        txtCategoria.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDescricao)
                                .addComponent(lblTituloEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNomeProduto)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                .addComponent(txtNomeProduto))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEstoque)
                                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoSugerido)
                            .addComponent(txtMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPrecoCusto)
                                        .addComponent(lblMargemLucro))
                                    .addGap(44, 44, 44))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblTituloCalculeLucro)
                                    .addGap(73, 73, 73)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(rbtnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoUnidade)
                            .addComponent(txtPrecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEstoqueAtual1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCategoria)))
                            .addComponent(btnConfirmarAlteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblTituloCalculeLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecoCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMargemLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecoSugerido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTituloEditarProduto)
                        .addGap(34, 34, 34)
                        .addComponent(lblNomeProduto)
                        .addGap(5, 5, 5)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstoqueAtual1)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAtivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnDesativar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecoUnidade)
                        .addGap(4, 4, 4)
                        .addComponent(txtPrecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarAlteracoes)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueActionPerformed

    private void rbtnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAtivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAtivarActionPerformed

    private void btnConfirmarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarAlteracoesActionPerformed
        // TODO add your handling code here:
        try {
            // Validação básica
            String nome = txtNomeProduto.getText().trim();
            String estoqueTexto = txtEstoque.getText().trim();
            String precoUnidadeTexto = txtPrecoUnidade.getText().trim();
            String precoCustoTexto = txtPrecoCusto.getText().trim();

            if (nome.isEmpty() || precoUnidadeTexto.isEmpty() || estoqueTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha o Nome, Estoque e Preço da unidade!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tratamento seguro de Números
            int estoque = Integer.parseInt(estoqueTexto);
            double precoUnidade = Double.parseDouble(precoUnidadeTexto.replace(",", "."));
            double precoCusto = precoCustoTexto.isEmpty() ? 0.0 : Double.parseDouble(precoCustoTexto.replace(",", "."));

            // Atualiza os dados do produto que estava na memória
            produtoEmEdicao.setNome(nome);
            produtoEmEdicao.setDescricao(txtDescricao.getText().trim());
            produtoEmEdicao.setQuantidadeEstoque(estoque);
            produtoEmEdicao.setPrecoUnidade(precoUnidade);
            produtoEmEdicao.setPrecoCusto(precoCusto);
            produtoEmEdicao.setAtivo(rbtnAtivar.isSelected()); // Lê o status da bolinha

            // Manda o Controller fazer o UPDATE no banco
            produtoController.update(produtoEmEdicao);

            JOptionPane.showMessageDialog(this, 
                "Produto atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Manda a tela de listagem atualizar a tabela e fecha a janela
            if (listarProdutos != null) {
                listarProdutos.atualizarTabela();
            }
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, digite apenas números válidos no Preço e no Estoque.", 
                "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao atualizar o produto: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarAlteracoesActionPerformed

    private void txtPrecoUnidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoUnidadeFocusGained
        // TODO add your handling code here:
                String textoAtual = txtPrecoUnidade.getText().trim();
        
        // Se o campo tiver zerado, ele limpa para facilitar a digitação
        if (textoAtual.equals("R$")) {
            txtPrecoUnidade.setText("");
        }
    }//GEN-LAST:event_txtPrecoUnidadeFocusGained

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        CategoriasDisponiveis dialog = new CategoriasDisponiveis(this, true);
        dialog.setListaCategorias(categoriaController.findAllAtivas());
        dialog.setVisible(true);

        // Quando o dialog fechar, pega a categoria que o usuário clicou
        Categoria selecionada = dialog.getCategoriaSelecionada();

        if (selecionada != null) {
            this.categoriaSelecionada = selecionada; // Atualiza a variável da memória
            txtCategoria.setText(selecionada.getNome()); // Atualiza o texto na tela
        }
    }//GEN-LAST:event_btnCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnConfirmarAlteracoes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblEstoqueAtual1;
    private javax.swing.JLabel lblMargemLucro;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPrecoCusto;
    private javax.swing.JLabel lblPrecoSugerido;
    private javax.swing.JLabel lblPrecoUnidade;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloCalculeLucro;
    private javax.swing.JLabel lblTituloEditarProduto;
    private javax.swing.JRadioButton rbtnAtivar;
    private javax.swing.JRadioButton rbtnDesativar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtMargemLucro;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCusto;
    private javax.swing.JTextField txtPrecoSugerido;
    private javax.swing.JTextField txtPrecoUnidade;
    // End of variables declaration//GEN-END:variables
}
