/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.venda.view;

import br.com.ifba.prg03projetosgcr.produto.entity.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
public class BuscaProduto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscaProduto.class.getName());
    
    private Produto produtoSelecionado;
    private List<Produto> listaProdutos;
    
    //Método para o PDV "pegar" o produto depois que a janela fechar
    public Produto getProdutoSelecionado() {
        return this.produtoSelecionado;
    }
    
    // Método para preencher a tabela (recebe a lista lá do PDV)
    public void setListaProdutos(List<Produto> produtos) {
        this.listaProdutos = produtos;
        atualizarTabelaBusca(produtos);
    }
    
    private void atualizarTabelaBusca(List<Produto> produtosParaMostrar) {
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0); // Limpa a tabela

        for (Produto p : produtosParaMostrar) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                String.format(java.util.Locale.US, "%.2f", p.getPrecoUnidade())
            });
        }
    }
    
    
    /**
     * Creates new form BuscaProduto
     */
    public BuscaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {
        String textoDigitado = txtBusca.getText().toLowerCase();
        List<Produto> produtosFiltrados = new ArrayList<>();
        
        for (Produto p : listaProdutos) {
            if (p.getNome().toLowerCase().contains(textoDigitado)) {
                produtosFiltrados.add(p);
            }
        }
        atualizarTabelaBusca(produtosFiltrados);
    }
    
    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {
        // Verifica se foi um duplo clique (clickCount == 2)
        if (evt.getClickCount() == 2) {
            int linhaClicada = tblProdutos.getSelectedRow();
            if (linhaClicada != -1) {
                // Pega o ID da primeira coluna da tabela
                Long idSelecionado = (Long) tblProdutos.getValueAt(linhaClicada, 0);
                
                // Acha o produto na lista e guarda na variável
                for (Produto p : listaProdutos) {
                    if (p.getId().equals(idSelecionado)) {
                        this.produtoSelecionado = p;
                        break;
                    }
                }
                this.dispose(); // Fecha a janelinha de busca
            }
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNome.setText("Digite o nome do produto:");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Produto", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 51));
        btnConfirmar.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnConfirmar.setText("Confirmar Seleção");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnConfirmar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // Pega a linha que o usuário clicou na tabela
        int linhaClicada = tblProdutos.getSelectedRow();
        
        // Se ele não clicou em nenhuma linha (linha -1), o sistema avisa
        if (linhaClicada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecione um produto na lista primeiro.", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Se clicou, faz o mesmo processo do duplo clique: pega o ID e acha o produto
        Long idSelecionado = (Long) tblProdutos.getValueAt(linhaClicada, 0);
        
        for (Produto p : listaProdutos) {
            if (p.getId().equals(idSelecionado)) {
                this.produtoSelecionado = p;
                break;
            }
        }
        
        // Fecha a janela
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BuscaProduto dialog = new BuscaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
