/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.venda.view;

import br.com.ifba.prg03projetosgcr.cliente.controller.ClienteController;
import br.com.ifba.prg03projetosgcr.cliente.entity.Cliente;
import br.com.ifba.prg03projetosgcr.cliente.view.components.BotaoCelulaRenderer;
import br.com.ifba.prg03projetosgcr.produto.controller.ProdutoController;
import br.com.ifba.prg03projetosgcr.produto.entity.Produto;
import br.com.ifba.prg03projetosgcr.pagamento.entity.FormaPagamento;
import br.com.ifba.prg03projetosgcr.venda.view.BuscaCliente;
import br.com.ifba.prg03projetosgcr.venda.controller.VendaController;
import br.com.ifba.prg03projetosgcr.venda.entity.ItemVenda;
import br.com.ifba.prg03projetosgcr.venda.entity.Venda;
import br.com.ifba.prg03projetosgcr.venda.view.components.CarrinhoBotaoEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class FrenteDeCaixa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrenteDeCaixa.class.getName());
    
    @Autowired
    private VendaController vendaController;
    @Autowired 
    private ProdutoController produtoController;
    @Autowired 
    private ClienteController clienteController;
    @Autowired
    private ApplicationContext context; // Para abrir os JDialogs
    
    private Venda vendaAtual = new Venda();
    /**
     * Creates new form FrenteDeCaixa
     */
    public FrenteDeCaixa() {
        initComponents();
        
        //limpa texto padrao do combobox
        cbxFormaPagamento.removeAllItems();
        
       //pxa opções do Enum para preencher
       for(FormaPagamento forma : FormaPagamento.values()){
           cbxFormaPagamento.addItem(forma.name());
       }
       
       
        //zera a qtnd de linhas da tabela para remover as linhas nulas
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
        
        tblCarrinho.getColumnModel().getColumn(5).setCellRenderer(new BotaoCelulaRenderer(tblCarrinho));
        tblCarrinho.getColumnModel().getColumn(5).setCellEditor(new CarrinhoBotaoEditor(tblCarrinho, this));
        
        //aumenta a altura das linhas da tablea
        tblCarrinho.setRowHeight(45);
        
        // Garante que a coluna tenha uma largura razoável para caber os 2 botões
        tblCarrinho.getColumnModel().getColumn(5).setPreferredWidth(110); 
        tblCarrinho.getColumnModel().getColumn(5).setMinWidth(110);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPdv = new javax.swing.JLabel();
        btnBuscarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        lblValorTotal = new javax.swing.JLabel();
        btnNomeCliente = new javax.swing.JButton();
        lblNomeCliente1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnFinalizarVenda = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        cbxFormaPagamento = new javax.swing.JComboBox<>();
        lblFormaPagamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloPdv.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        lblTituloPdv.setText("Realize uma venda (PDV)");

        btnBuscarProduto.setBackground(new java.awt.Color(0, 102, 51));
        btnBuscarProduto.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBuscarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProduto.setText("Buscar Produto");
        btnBuscarProduto.addActionListener(this::btnBuscarProdutoActionPerformed);

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Qtd", "Valor Unit.", "Subtotal", "Ações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrinho);

        lblValorTotal.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblValorTotal.setText("R$");

        btnNomeCliente.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnNomeCliente.setText("Informar Cliente");
        btnNomeCliente.addActionListener(this::btnNomeClienteActionPerformed);

        lblNomeCliente1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNomeCliente1.setText("Cliente:");

        lblTotal.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTotal.setText("Total:");

        btnFinalizarVenda.setBackground(new java.awt.Color(51, 51, 51));
        btnFinalizarVenda.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnFinalizarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarVenda.setText("Finalizar Venda");
        btnFinalizarVenda.addActionListener(this::btnFinalizarVendaActionPerformed);

        btnCancelarVenda.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda");
        btnCancelarVenda.addActionListener(this::btnCancelarVendaActionPerformed);

        cbxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxFormaPagamento.addActionListener(this::cbxFormaPagamentoActionPerformed);

        lblFormaPagamento.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblFormaPagamento.setText("Forma de Pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloPdv, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal)
                    .addComponent(lblTotal)
                    .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(btnNomeCliente)
                    .addComponent(lblNomeCliente1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTituloPdv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarProduto)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNomeCliente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNomeCliente)
                        .addGap(18, 18, 18)
                        .addComponent(lblFormaPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTotal)
                        .addGap(63, 63, 63)
                        .addComponent(btnFinalizarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarVenda)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomeClienteActionPerformed
        // Abre a janela de busca de clientes
        BuscaCliente busca = new BuscaCliente(this, true);
            
        //Busca todos os clientes no banco e entrega para a tabela da janela
        busca.setListaClientes(clienteController.findAll());
        busca.setVisible(true); // O sistema pausa aqui até a janela fechar

        // Quando a janela fecha, o sistema captura quem foi selecionado
        Cliente selecionado = busca.getClienteSelecionado();
        
        // Se o usuário escolheu alguém (não cancelou a tela)
        if (selecionado != null) {
            // Salva o cliente no carrinho atual!
            vendaAtual.setCliente(selecionado);

            btnNomeCliente.setText(selecionado.getNome());
        }
    }//GEN-LAST:event_btnNomeClienteActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        
        //Verifica se tem algo no carrinho
        if (vendaAtual.getItens().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O carrinho está vazio!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try{
            // Lê a forma de pagamento direto na tela
            String opcaoSelecionada = cbxFormaPagamento.getSelectedItem().toString();
            FormaPagamento formaEscolhida = FormaPagamento.valueOf(opcaoSelecionada);
            
            vendaAtual.setFormaPagamento(formaEscolhida);
            
            //aciona o controller para salvar no banco
            vendaController.realizarVenda(vendaAtual);
                
            JOptionPane.showMessageDialog(this, "Venda Finalizada com Sucesso!",
                    "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            //limpa a tela para o proximo cliente
            vendaAtual = new Venda();
            btnNomeCliente.setText("Informar Cliente");
            ((DefaultTableModel) tblCarrinho.getModel()).setNumRows(0);
            atualizarTotalVisor();
        } catch (Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", 
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void cbxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFormaPagamentoActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
       
        //abre a tela de busca
        BuscaProduto busca = new BuscaProduto(this, true);
        
        busca.setListaProdutos(produtoController.findAllAtivos()); //entrega os produtos
        busca.setVisible(true); 
        
        //Quando a janela fechar, verifica se ele escolheu algo
        Produto selecionado = busca.getProdutoSelecionado();
        
        if (selecionado != null){
            //pergunta a quantidade (padrão vai ser 1)
            String qtdStr = JOptionPane.showInputDialog(this, "Quantidade:", "1");
            if(qtdStr != null & !qtdStr.trim().isEmpty()){
                try{
                    int qtd = Integer.parseInt(qtdStr);
                    adicionarProdutoAoCarrinho(selecionado, qtd);
                } catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Quantidade inválida!");
                }
            }
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed
    
    private void adicionarProdutoAoCarrinho(Produto produto, int quantidade) {
        // Cria a linha do pedido
        ItemVenda novoItem = new ItemVenda();
        novoItem.setProduto(produto);
        novoItem.setQuantidade(quantidade);
        novoItem.setPrecoUnitario(produto.getPrecoUnidade());
        novoItem.setSubtotal(produto.getPrecoUnidade() * quantidade);
        novoItem.setVenda(vendaAtual); // Conecta o item à venda atual

        // Adiciona na lista
        vendaAtual.getItens().add(novoItem);

        // Adiciona na Tabela visual
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
        modelo.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            quantidade,
            String.format("R$ %.2f", produto.getPrecoUnidade()),
            String.format("R$ %.2f", novoItem.getSubtotal())
        });

        atualizarTotalVisor();
    }

    private void atualizarTotalVisor() {
        double total = 0.0;
        for (ItemVenda item : vendaAtual.getItens()) {
            total += item.getSubtotal();
        }
        // lblTotal é aquele JLabel gigante na sua direita
        lblValorTotal.setText(String.format("R$ %.2f", total)); 
    }
    
    public void editarQuantidadeItem(int linha) {
        ItemVenda item = vendaAtual.getItens().get(linha);
        String nomeProduto = item.getProduto().getNome();
        
        String input = JOptionPane.showInputDialog(this, 
                "Nova quantidade para " + nomeProduto + ":", item.getQuantidade());
                
        if (input != null && !input.trim().isEmpty()) {
            try {
                int novaQtd = Integer.parseInt(input);
                if (novaQtd > 0) {
                    // Atualiza o objeto no back-end
                    item.setQuantidade(novaQtd);
                    item.setSubtotal(item.getPrecoUnitario() * novaQtd);
                    
                    // Atualiza os valores visuais na Tabela
                    DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
                    modelo.setValueAt(novaQtd, linha, 1); // Atualiza a coluna 1 (Qtd)
                    modelo.setValueAt(String.format("R$ %.2f", item.getSubtotal()), linha, 3); // Atualiza a coluna 3 (Subtotal)
                    
                    // Recalcula o valor total da venda
                    atualizarTotalVisor();
                } else {
                    JOptionPane.showMessageDialog(this, "A quantidade deve ser maior que zero!");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Quantidade inválida!");
            }
        }
    }
    
    public void removerItemCarrinho(int linha) {
        ItemVenda item = vendaAtual.getItens().get(linha);
        
        int resposta = JOptionPane.showConfirmDialog(this, 
            "Deseja remover '" + item.getProduto().getNome() + "' do carrinho?", 
            "Remover Item", JOptionPane.YES_NO_OPTION);
            
        if (resposta == JOptionPane.YES_OPTION) {
            // Remove da lista em memória
            vendaAtual.getItens().remove(linha);
            
            // Remove da tabela visual
            DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
            modelo.removeRow(linha);
            
            atualizarTotalVisor();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrenteDeCaixa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnNomeCliente;
    private javax.swing.JComboBox<String> cbxFormaPagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblNomeCliente1;
    private javax.swing.JLabel lblTituloPdv;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblCarrinho;
    // End of variables declaration//GEN-END:variables
}
