/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.cliente.view;

import br.com.ifba.prg03projetosgcr.cliente.controller.ClienteController;
import br.com.ifba.prg03projetosgcr.cliente.entity.Cliente;
import br.com.ifba.prg03projetosgcr.cliente.entity.Endereco;
import br.com.ifba.prg03projetosgcr.cliente.service.ClienteService;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */

@Component
public class EditarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCliente.class.getName());
    
    private ListarClientes listarClientes;
    @Autowired
    private ClienteController clienteController;
    //variavel para guardar o cliente selecionado 
    private Cliente clienteAtual;
    
    /**
     * Creates new form EditarCliente
     */
    public EditarCliente() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        //cria o grupo de botoes
        javax.swing.ButtonGroup grupoEndereco = new javax.swing.ButtonGroup();
        
        //adiciona as checkboxes ao grupo
        grupoEndereco.add(cbxEnderecoNao);
        grupoEndereco.add(cbxEnderecoSim);
        
    }
    
    public void setListarClientes(ListarClientes listarClientes){
        this.listarClientes = listarClientes;
    }
    
    public void preencherCampos(Cliente cliente){
        //Salva a referencia do cliente
        this.clienteAtual = cliente;
        
        txtNome.setText(cliente.getNome());
        txtTelefone.setText(cliente.getTelefone());
        
        //verifica se o cliente tem um endereço vinculado
        if(cliente.getEndereco() != null){
            cbxEnderecoSim.setSelected(true);
            txtBairro.setText(cliente.getEndereco().getBairro());
            txtRua.setText(cliente.getEndereco().getRua());
            txtNumero.setText(cliente.getEndereco().getNumero());
            txtPntReferencia.setText(cliente.getEndereco().getPontoReferencia());
        } else{
            //caso cliente não tenha endereço, limpa os campos
            cbxEnderecoNao.setSelected(true);
            txtBairro.setText("");
            txtRua.setText("");
            txtNumero.setText("");
            txtPntReferencia.setText("");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtOpcaoEndereco = new javax.swing.JLabel();
        cbxEnderecoSim = new javax.swing.JCheckBox();
        cbxEnderecoNao = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblPntReferencia = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtPntReferencia = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setText("Editar Cliente");

        lblBairro.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblBairro.setText("Bairro:");

        lblTelefone.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblTelefone.setText("Telefone:");

        txtOpcaoEndereco.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtOpcaoEndereco.setText("Deseja cadastrar o endereço?");

        cbxEnderecoSim.setText("Sim");

        cbxEnderecoNao.setText("Não");
        cbxEnderecoNao.addActionListener(this::cbxEnderecoNaoActionPerformed);

        lblNome.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblNome.setText("Nome:");

        lblRua.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblRua.setText("Rua:");

        lblNumero.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblNumero.setText("Número:");

        lblPntReferencia.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblPntReferencia.setText("Ponto de Referência:");

        txtBairro.addActionListener(this::txtBairroActionPerformed);

        txtRua.addActionListener(this::txtRuaActionPerformed);

        txtNumero.addActionListener(this::txtNumeroActionPerformed);

        txtPntReferencia.addActionListener(this::txtPntReferenciaActionPerformed);

        lblDescricao.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        lblDescricao.setText("Os espaços não preenchidos seram mantidos como estão.");

        btnSalvar.setBackground(new java.awt.Color(0, 102, 0));
        btnSalvar.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Editar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNumero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtOpcaoEndereco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxEnderecoSim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxEnderecoNao))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPntReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPntReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefone)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOpcaoEndereco)
                        .addComponent(cbxEnderecoSim)
                        .addComponent(cbxEnderecoNao))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBairro)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRua)
                        .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumero)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPntReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPntReferencia))
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEnderecoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEnderecoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEnderecoNaoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtPntReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPntReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPntReferenciaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            // Só altera se o campo não estiver vazio 
            if(!txtNome.getText().trim().isEmpty()){
                clienteAtual.setNome(txtNome.getText().trim());
            }
            if (!txtTelefone.getText().trim().isEmpty()) {
                clienteAtual.setTelefone(txtTelefone.getText().trim());
            }

            // Verifica se a opção de endereço está marcada como Sim
            if (cbxEnderecoSim.isSelected()) {
                Endereco endereco = clienteAtual.getEndereco();

                // Se o cliente não tinha endereço cadastrado antes, criamos um novo
                if (endereco == null) {
                    endereco = new Endereco();
                    clienteAtual.setEndereco(endereco);
                }

                // Aplica a mesma regra de não subscrever se estiver vazio
                if (!txtBairro.getText().trim().isEmpty()) {
                    endereco.setBairro(txtBairro.getText().trim());
                }
                if (!txtRua.getText().trim().isEmpty()) {
                    endereco.setRua(txtRua.getText().trim());
                }
                if (!txtNumero.getText().trim().isEmpty()) {
                    endereco.setNumero(txtNumero.getText().trim());
                }
                if (!txtPntReferencia.getText().trim().isEmpty()) {
                    endereco.setPontoReferencia(txtPntReferencia.getText().trim());
                }
            } else {
                // Se o usuário marcou "Não" para o endereço, removemos o vinculo
                clienteAtual.setEndereco(null); 
            }
            
            //envia o objeto atualizado ao controller
            clienteController.update(clienteAtual);
            
            JOptionPane.showMessageDialog(this,
                    "Cliente atualizado com Sucesso",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
                    
            //avisa a tela principal para recarregar a tabela com os novos dados
            if(listarClientes != null){
                listarClientes.atualizarTabela();
            }
            dispose();
        } catch(RuntimeException ex){
            javax.swing.JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Aviso de Validação",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,
                "Erro interno ao atualizar dados do cliente",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbxEnderecoNao;
    private javax.swing.JCheckBox cbxEnderecoSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPntReferencia;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JLabel txtOpcaoEndereco;
    private javax.swing.JTextField txtPntReferencia;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
