/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.cliente.view;

import br.com.ifba.prg03projetosgcr.cliente.view.components.BotaoCelulaRenderer;
import br.com.ifba.prg03projetosgcr.cliente.view.components.BotaoCelulaEditor;
import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class ListarClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarClientes.class.getName());
    
    @Autowired
    private ApplicationContext context;
    public ListarClientes() {
        initComponents();
        
        JPanel painelPrincipal = new JPanel();
        // Define o tamanho ideal apenas do conteúdo        
        painelPrincipal.setPreferredSize(new Dimension(1280,720));
        
        add(painelPrincipal);
        
        // O 'pack' empacota a janela para ela se ajustar ao tamanho do painel
        pack();
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        //zera a qtnd de linhas da tabela para remover as linhas nulas
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
        
        //aumenta a altura das linhas da tablea
        tblClientes.setRowHeight(45);
        
        //Configurar a coluna de ações com botoes de editar e deletar
        configurarColunaAcoes();
    }
    
    private void configurarColunaAcoes(){
        //criar o renderer personalizado para a coluna acoes 
        BotaoCelulaRenderer renderer = new BotaoCelulaRenderer(tblClientes);
        
        //obter a coluna de acoes
        TableColumn colunaAcoes = tblClientes.getColumnModel().getColumn(3);
        colunaAcoes.setCellRenderer(renderer);
        colunaAcoes.setCellEditor(new BotaoCelulaEditor(tblClientes, this));
        
        
    }
    
    public void editarCliente(int linha){
        //obter os dados da linha
        Object valorCliente = tblClientes.getValueAt(linha, 0);
        
        //criar e configurar a tela de edição
        EditarCliente telaEditar = context.getBean(EditarCliente.class);
        telaEditar.preencherCampos(valorCliente != null ? valorCliente.toString() : "");
        telaEditar.setListarClientes(this);
        telaEditar.setVisible(true);

    }
    
    public void deletarCliente(int linha){
        Object valorCliente = tblClientes.getValueAt(linha, 0);
        
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Tem ceteza que deseja deletar o cliente: " + valorCliente + "?", 
            "Confirmar Exclusão", 
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);
        
        if(confirmacao == javax.swing.JOptionPane.YES_OPTION){
            //remove a linha da tabela
            DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
            modelo.removeRow(linha);
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cliente deletado com sucesso",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void abrirTelaCadastro(){
        // como a tela é prototype, o context.getBean cria uma tela zerada toda vez
        CadastrarClientes telaCadastro = context.getBean(CadastrarClientes.class);
        telaCadastro.setListarClientes(this);
        telaCadastro.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnCadastrarCliente = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 214, 214));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Gestão de Clientes");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Dívida Total", "Contato", "Ações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        btnCadastrarCliente.setBackground(new java.awt.Color(0, 102, 51));
        btnCadastrarCliente.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.addActionListener(this::btnCadastrarClienteActionPerformed);

        txtPesquisa.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtPesquisa.setText("Pesquise por nome...");
        txtPesquisa.addActionListener(this::txtPesquisaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarCliente)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastrarCliente))
                .addGap(12, 12, 12)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        // TODO add your handling code here:
        abrirTelaCadastro();

    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListarClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
