/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.categoria.view;

import br.com.ifba.prg03projetosgcr.categoria.controller.CategoriaController;
import br.com.ifba.prg03projetosgcr.categoria.entity.Categoria;
import br.com.ifba.prg03projetosgcr.config.SpringContext;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class CadastrarCategoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarCategoria.class.getName());
    
    @Autowired
    private CategoriaController categoriaController;
    
    /**
     * Creates new form CadastrarCategoria
     */
    public CadastrarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblDisponivel = new javax.swing.JLabel();
        rbtnAtivado = new javax.swing.JRadioButton();
        rbtnDesativado = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastre uma nova categoria");

        lblNome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblDescricao.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblDisponivel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDisponivel.setText("Disponibilidade:");

        buttonGroup1.add(rbtnAtivado);
        rbtnAtivado.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbtnAtivado.setSelected(true);
        rbtnAtivado.setText("Ativado");

        buttonGroup1.add(rbtnDesativado);
        rbtnDesativado.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbtnDesativado.setText("Desativado");
        rbtnDesativado.addActionListener(this::rbtnDesativadoActionPerformed);

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 51));
        btnCadastrar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar Categoria");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 173, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDescricao)
                        .addComponent(lblNome)
                        .addComponent(lblDisponivel)
                        .addComponent(rbtnAtivado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtnDesativado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addComponent(txtNome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addGap(4, 4, 4)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDisponivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAtivado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnDesativado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDesativadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDesativadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDesativadoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        // Resgata os textos digitados e remove espaços em branco nas pontas
        String nome = txtNome.getText().trim();
        String descricao = txtDescricao.getText().trim();

        // Validação visual básica antes de tentar enviar pro controller
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "O campo 'Nome' é obrigatório.", 
                "Aviso de Validação", 
                JOptionPane.WARNING_MESSAGE);
            return; // Para a execução aqui e não tenta salvar
        }

        try {
            // Instancia a nova entidade
            Categoria categoria = new Categoria();
            categoria.setNome(nome);
            categoria.setDescricao(descricao);
            // O campo "ativo" não precisa ser setado, pois na Entidade ele já nasce como "true" por padrão.

            categoriaController.save(categoria);

            // Mensagem de sucesso
            JOptionPane.showMessageDialog(this, 
                "Categoria cadastrada com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);

            this.dispose(); 

        } catch (Exception e) {
            // Se a camada Service barrar o salvamento, o erro cai aqui e é mostrado na tela
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar a categoria: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDisponivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnAtivado;
    private javax.swing.JRadioButton rbtnDesativado;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
