/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.prg03projetosgcr.categoria.view;

import br.com.ifba.prg03projetosgcr.categoria.controller.CategoriaController;
import br.com.ifba.prg03projetosgcr.categoria.entity.Categoria;
import br.com.ifba.prg03projetosgcr.config.SpringContext;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author joaol
 */
@Component
public class EditarCategoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCategoria.class.getName());
    
    @Autowired
    private CategoriaController categoriaController;
    
    private ListarCategorias listarCategorias;
    private Categoria categoriaEmEdicao; 
    private ButtonGroup grupoStatus;

    public void setListarCategorias(ListarCategorias listarCategorias) {
        this.listarCategorias = listarCategorias;
    }
    
    public void preencherCampos(Categoria categoria) {
        this.categoriaEmEdicao = categoria; // Guarda o produto na memória
        
        // Joga os dados do banco para os campos de texto da tela
        txtNome.setText(categoria.getNome());
        txtDescricao.setText(categoria.getDescricao() != null ? categoria.getDescricao() : "");
        
        // Marca a bolinha de status correta
        if (categoria.isAtivo()) {
            rbtnAtivado.setSelected(true);
        } else {
            rbtnDesativado.setSelected(true); 
        }
        
    }
    /**
     * Creates new form EditarCategoria
     */
    public EditarCategoria() {
        initComponents();
        
        grupoStatus = new ButtonGroup();
        grupoStatus.add(rbtnAtivado);
        grupoStatus.add(rbtnDesativado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblDisponivel = new javax.swing.JLabel();
        rbtnAtivado = new javax.swing.JRadioButton();
        rbtnDesativado = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEditar.setBackground(new java.awt.Color(0, 102, 51));
        btnEditar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar Categoria");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblTitulo.setText("Edite a categoria");

        lblNome.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblDescricao.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblDisponivel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDisponivel.setText("Disponibilidade:");

        rbtnAtivado.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbtnAtivado.setSelected(true);
        rbtnAtivado.setText("Ativado");

        rbtnDesativado.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        rbtnDesativado.setText("Desativado");
        rbtnDesativado.addActionListener(this::rbtnDesativadoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 194, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescricao)
                    .addComponent(lblNome)
                    .addComponent(lblDisponivel)
                    .addComponent(rbtnAtivado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnDesativado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(69, 69, 69)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addGap(4, 4, 4)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDisponivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAtivado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnDesativado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDesativadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDesativadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDesativadoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText().trim();
        String descricao = txtDescricao.getText().trim();
        
        // Validação básica
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "O campo 'Nome' é obrigatório.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Atualiza o objeto que já possui o ID preenchido
            categoriaEmEdicao.setNome(nome);
            categoriaEmEdicao.setDescricao(descricao);
            categoriaEmEdicao.setAtivo(rbtnAtivado.isSelected()); // Pega o status diretamente da interface
            
            // Envia para o banco de dados via controller
            categoriaController.update(categoriaEmEdicao);
            
            JOptionPane.showMessageDialog(this, 
                "Categoria atualizada com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
                
            // Recarrega a JTable da tela ListarCategorias para refletir a mudança instantaneamente
            if (listarCategorias != null) {
                listarCategorias.atualizarTabela();
            }
            
            // Fecha a janela de edição
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao atualizar a categoria: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarCategoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDisponivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnAtivado;
    private javax.swing.JRadioButton rbtnDesativado;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
